
CREATE DATABASE IF NOT EXISTS deveops;

USE deveops;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL
    phone VARCHAR(20),
    address VARCHAR(255);
);


